#La API de Detección de Objetos de TensorFlow es un entorno de código abierto desarrollado sobre TensorFlow que facilita la creación, entrenamiento e implementación de modelos de visión por computadora. Estos modelos son capaces de localizar e identificar múltiples objetos dentro de una misma imagen.

#Esta API es compatible con TensorFlow 2.x, lo que permite una ejecución inmediata (Eager Execution) para una depuración más rápida y estrategias sencillas de distribución en múltiples GPUs o TPUs.

#En este tutorial veremos la introducción básica y cómo utilizar un modelo preentrenado para realizar inferencias (detecciones) de inmediato.